import { Gift } from './types';

export const GIFTS: Gift[] = [
    { id: 'gift-1', name: 'Coração', price: 1, image: '❤️', category: 'Popular' },
    { id: 'gift-2', name: 'Café', price: 3, image: '☕', category: 'Popular' },
    { id: 'gift-3', name: 'Milho', price: 2, image: '🍿', category: 'Popular' },
    { id: 'gift-4', name: 'Rosa', price: 5, image: '🌷', category: 'Popular' },
    { id: 'gift-5', name: 'Flor', price: 7, image: '🌸', category: 'Popular' },
    { id: 'gift-6', name: 'Donut', price: 8, image: '🍩', category: 'Popular' },
    { id: 'gift-7', name: 'Balão', price: 9, image: '🎈', category: 'Popular' },
    { id: 'gift-8', name: 'Batom', price: 10, image: '💄', category: 'Popular' },
    { id: 'gift-9', name: 'Sinal de Luz do Ventilador', price: 10, image: '🌟', category: 'Popular' },
    { id: 'gift-10', name: 'Chocolate', price: 12, image: '🍫', category: 'Popular' },
    { id: 'gift-11', name: 'Sorvete', price: 15, image: '🍦', category: 'Popular' },
    { id: 'gift-12', name: 'Lanche', price: 20, image: '🍔', category: 'Popular' },
    { id: 'gift-13', name: 'Perfume', price: 25, image: '🧴', category: 'Popular' },
    { id: 'gift-14', name: 'Pirulito', price: 30, image: '🍭', category: 'Popular' },
    { id: 'gift-15', name: 'Pizza', price: 35, image: '🍕', category: 'Popular' },
    { id: 'gift-16', name: 'Microfone', price: 40, image: '🎤', category: 'Popular' },
    { id: 'gift-17', name: 'Alvo', price: 50, image: '🎯', category: 'Popular' },
    { id: 'gift-18', name: 'Câmera', price: 60, image: '📸', category: 'Popular' },
    { id: 'gift-19', name: 'Óculos de Sol', price: 80, image: '😎', category: 'Popular' },
    { id: 'gift-20', name: 'Panda', price: 65, image: '🐼', category: 'Popular' },
    { id: 'gift-21', name: 'Coala', price: 68, image: '🐨', category: 'Popular' },
    { id: 'gift-22', name: 'Fatia de Pizza', price: 10, image: '🍕', category: 'Popular' },
    { id: 'gift-23', name: 'Taco', price: 15, image: '🌮', category: 'Popular' },
    { id: 'gift-24', name: 'Biscoito', price: 5, image: '🍪', category: 'Popular' },
    { id: 'gift-25', name: 'Cupcake', price: 8, image: '🧁', category: 'Popular' },
    { id: 'gift-26', name: 'Morango', price: 12, image: '🍓', category: 'Popular' },
    { id: 'gift-27', name: 'Abacate', price: 18, image: '🥑', category: 'Popular' },
    { id: 'gift-28', name: 'Brócolis', price: 4, image: '🥦', category: 'Popular' },
    { id: 'gift-29', name: 'Baguete', price: 6, image: '🥖', category: 'Popular' },
    { id: 'gift-30', name: 'Pretzel', price: 7, image: '🥨', category: 'Popular' },
    { id: 'gift-31', name: 'Queijo', price: 11, image: '🧀', category: 'Popular' },
    { id: 'gift-32', name: 'Waffle', price: 14, image: '🧇', category: 'Popular' },
    { id: 'gift-33', name: 'Panquecas', price: 16, image: '🥞', category: 'Popular' },
    { id: 'gift-34', name: 'Bacon', price: 19, image: '🥓', category: 'Popular' },
    { id: 'gift-35', name: 'Cachorro-quente', price: 22, image: '🌭', category: 'Popular' },
    { id: 'gift-36', name: 'Batata Frita', price: 9, image: '🍟', category: 'Popular' },
    { id: 'gift-37', name: 'Sanduíche', price: 24, image: '🥪', category: 'Popular' },
    { id: 'gift-38', name: 'Dango', price: 13, image: '🍡', category: 'Popular' },
    { id: 'gift-39', name: 'Onigiri', price: 5, image: '🍙', category: 'Popular' },
    { id: 'gift-40', name: 'Camarão Frito', price: 28, image: '🍤', category: 'Popular' },
    { id: 'gift-41', name: 'Sushi', price: 33, image: '🍣', category: 'Popular' },
    { id: 'gift-42', name: 'Taça de Sorvete', price: 17, image: '🍨', category: 'Popular' },
    { id: 'gift-43', name: 'Torta', price: 21, image: '🥧', category: 'Popular' },
    { id: 'gift-44', name: 'Doce', price: 3, image: '🍬', category: 'Popular' },
    { id: 'gift-45', name: 'Mel', price: 26, image: '🍯', category: 'Popular' },
    { id: 'gift-46', name: 'Copo de Leite', price: 8, image: '🥛', category: 'Popular' },
    { id: 'gift-47', name: 'Chá Verde', price: 10, image: '🍵', category: 'Popular' },
    { id: 'gift-48', name: 'Saquê', price: 29, image: '🍶', category: 'Popular' },
    { id: 'gift-49', name: 'Cerveja', price: 15, image: '🍺', category: 'Popular' },
    { id: 'gift-50', name: 'Milkshake', price: 22, image: '🥤', category: 'Popular' },
    { id: 'gift-51', name: 'Croissant', price: 11, image: '🥐', category: 'Popular' },
    { id: 'gift-52', name: 'Uvas', price: 14, image: '🍇', category: 'Popular' },
    { id: 'gift-53', name: 'Frango Frito', price: 27, image: '🍗', category: 'Popular' },
    { id: 'gift-54', name: 'Melancia', price: 10, image: '🍉', category: 'Popular' },

    { id: 'gift-55', name: 'Bola de Basquete', price: 70, image: '🏀', category: 'Atividade' },
    { id: 'gift-56', name: 'Bola', price: 75, image: '⚽', category: 'Atividade' },
    { id: 'gift-57', name: 'Túmulo', price: 99, image: '🪦', category: 'Atividade' },
    { id: 'gift-58', name: 'Bicicleta', price: 110, image: '🚲', category: 'Atividade' },
    { id: 'gift-59', name: 'Haltere', price: 120, image: '💪', category: 'Atividade' },
    { id: 'gift-60', name: 'Skate', price: 130, image: '🛹', category: 'Atividade' },
    { id: 'gift-61', name: 'Prancha de Surf', price: 140, image: '🏄', category: 'Atividade' },
    { id: 'gift-62', name: 'Luva de Boxe', price: 160, image: '🥊', category: 'Atividade' },
    { id: 'gift-63', name: 'Taco de Golfe', price: 180, image: '🏌️', category: 'Atividade' },
    { id: 'gift-64', name: 'Capacete de Corrida', price: 210, image: '⛑️', category: 'Atividade' },
    { id: 'gift-65', name: 'Bola de Tênis', price: 85, image: '🎾', category: 'Atividade' },
    { id: 'gift-66', name: 'Boliche', price: 95, image: '🎳', category: 'Atividade' },
    { id: 'gift-67', name: 'Bola de Rugby', price: 105, image: '🏉', category: 'Atividade' },
    { id: 'gift-68', name: 'Voleibol', price: 90, image: '🏐', category: 'Atividade' },
    { id: 'gift-69', name: 'Beisebol', price: 80, image: '⚾', category: 'Atividade' },
    { id: 'gift-70', name: 'Pingue-pongue', price: 78, image: '🏓', category: 'Atividade' },
    { id: 'gift-71', name: 'Badminton', price: 82, image: '🏸', category: 'Atividade' },
    { id: 'gift-72', name: 'Hóquei no Gelo', price: 150, image: '🏒', category: 'Atividade' },
    { id: 'gift-73', name: 'Hóquei de Campo', price: 145, image: '🏑', category: 'Atividade' },
    { id: 'gift-74', name: 'Lacrosse', price: 155, image: '🥍', category: 'Atividade' },
    { id: 'gift-75', name: 'Críquete', price: 115, image: '🏏', category: 'Atividade' },
    { id: 'gift-76', name: 'Rede de Gol', price: 190, image: '🥅', category: 'Atividade' },
    { id: 'gift-77', name: 'Pipa', price: 65, image: '🪁', category: 'Atividade' },
    { id: 'gift-78', name: 'Frisbee', price: 55, image: '🥏', category: 'Atividade' },
    { id: 'gift-79', name: 'Trenzinho', price: 220, image: '🛷', category: 'Atividade' },
    { id: 'gift-80', name: 'Pedra de Curling', price: 230, image: '🥌', category: 'Atividade' },
    { id: 'gift-81', name: 'Esquis', price: 250, image: '🎿', category: 'Atividade' },
    { id: 'gift-82', name: 'Dardos', price: 45, image: '🎯', category: 'Atividade' },
    { id: 'gift-83', name: 'Ioiô', price: 35, image: '🪀', category: 'Atividade' },
    { id: 'gift-84', name: 'Bumerangue', price: 40, image: '🪃', category: 'Atividade' },
    { id: 'gift-85', name: 'Trenó', price: 170, image: '🛷', category: 'Atividade' },
    { id: 'gift-86', name: 'Arco e Flecha', price: 190, image: '🏹', category: 'Atividade' },
    { id: 'gift-87', name: 'Patins', price: 135, image: '🛼', category: 'Atividade' },

    { id: 'gift-88', name: 'Urso', price: 500, image: '🧸', category: 'Luxo' },
    { id: 'gift-89', name: 'Boia', price: 800, image: '🍩', category: 'Luxo' },
    { id: 'gift-90', name: 'Champanhe', price: 1200, image: '🍾', category: 'Luxo' },
    { id: 'gift-91', name: 'Gema de Nível', price: 1500, image: '💎', category: 'Luxo' },
    { id: 'gift-92', name: 'Relógio', price: 2000, image: '⌚', category: 'Luxo' },
    { id: 'gift-93', name: 'Bolsa', price: 2500, image: '👜', category: 'Luxo' },
    { id: 'gift-94', name: 'Moto', price: 3000, image: '🛵', category: 'Luxo' },
    { id: 'gift-95', name: 'Violino', price: 3500, image: '🎻', category: 'Luxo' },
    { id: 'gift-96', name: 'Salto Alto', price: 4000, image: '👠', category: 'Luxo' },
    { id: 'gift-97', name: 'Piano', price: 4500, image: '🎹', category: 'Luxo' },
    { id: 'gift-98', name: 'Colar', price: 4800, image: '📿', category: 'Luxo' },
    { id: 'gift-99', name: 'Coroa', price: 5000, image: '👑', category: 'Luxo' },
    { id: 'gift-100', name: 'Bolsa de Grife', price: 6000, image: '👜', category: 'Luxo' },
    { id: 'gift-101', name: 'Diamante Azul', price: 6000, image: '💠', category: 'Luxo' },
    { id: 'gift-102', name: 'Carro Esportivo', price: 8888, image: '🏎️', category: 'Luxo' },
    { id: 'gift-103', name: 'Jóia Rara', price: 12000, image: '💍', category: 'Luxo' },
    { id: 'gift-104', name: 'Barco a Vela', price: 9000, image: '⛵', category: 'Luxo' },
    { id: 'gift-105', name: 'Navio de Cruzeiro', price: 15000, image: '🛳️', category: 'Luxo' },
    { id: 'gift-106', name: 'Sino', price: 1800, image: '🔔', category: 'Luxo' },
    { id: 'gift-107', name: 'Trompete', price: 2200, image: '🎺', category: 'Luxo' },
    { id: 'gift-108', name: 'Saxofone', price: 2800, image: '🎷', category: 'Luxo' },
    { id: 'gift-109', name: 'Acordeão', price: 3200, image: '🪗', category: 'Luxo' },
    { id: 'gift-110', name: 'Harpa', price: 4200, image: '🎻', category: 'Luxo' },
    { id: 'gift-111', name: 'Xadrez', price: 1000, image: '♟️', category: 'Luxo' },
    { id: 'gift-112', name: 'Jóia', price: 7500, image: '💎', category: 'Luxo' },
    { id: 'gift-113', name: 'Mala de Dinheiro', price: 10000, image: '💰', category: 'Luxo' },
    { id: 'gift-114', name: 'Carta de Baralho', price: 900, image: '🃏', category: 'Luxo' },
    { id: 'gift-115', name: 'Telescópio', price: 5500, image: '🔭', category: 'Luxo' },
    { id: 'gift-116', name: 'Microscópio', price: 5200, image: '🔬', category: 'Luxo' },
    { id: 'gift-117', name: 'Ampulheta', price: 1300, image: '⏳', category: 'Luxo' },
    { id: 'gift-118', name: 'Despertador', price: 1100, image: '⏰', category: 'Luxo' },
    { id: 'gift-119', name: 'Globo', price: 3800, image: '🌍', category: 'Luxo' },
    { id: 'gift-120', name: 'Balão de Ar Quente', price: 4600, image: '🎈', category: 'Luxo' },
    { id: 'gift-121', name: 'Troféu', price: 9999, image: '🏆', category: 'Luxo' },
    { id: 'gift-122', name: 'Barra de Ouro', price: 7000, image: '🧈', category: 'Luxo' },
    { id: 'gift-123', name: 'Cofre de Diamantes', price: 11000, image: '💰', category: 'Luxo' },
    { id: 'gift-124', name: 'Chave do Carro', price: 9500, image: '🔑', category: 'Luxo' },
    { id: 'gift-125', name: 'Cetro Real', price: 13000, image: '👑', category: 'Luxo' },
    { id: 'gift-202', name: 'Vulcão de Dinheiro', price: 20000, image: '🌋💰', category: 'Luxo' },

    { id: 'gift-126', name: 'Foguete', price: 500, image: '🚀', category: 'VIP' },
    { id: 'gift-127', name: 'Jato Privado', price: 600, image: '✈️', category: 'VIP' },
    { id: 'gift-128', name: 'Anel', price: 750, image: '💍', category: 'VIP' },
    { id: 'gift-129', name: 'Leão', price: 800, image: '🦁', category: 'VIP' },
    { id: 'gift-130', name: 'Carro', price: 1000, image: '🚗', category: 'VIP' },
    { id: 'gift-131', name: 'Fênix', price: 1200, image: '🔥', category: 'VIP' },
    { id: 'gift-132', name: 'Supercarro', price: 1500, image: '🏎️', category: 'VIP' },
    { id: 'gift-133', name: 'Dragão', price: 1800, image: '🐉', category: 'VIP' },
    { id: 'gift-134', name: 'Castelo', price: 2000, image: '🏰', category: 'VIP' },
    { id: 'gift-135', name: 'Universo', price: 2500, image: '🌌', category: 'VIP' },
    { id: 'gift-136', name: 'Helicóptero', price: 3000, image: '🚁', category: 'VIP' },
    { id: 'gift-137', name: 'Planeta', price: 4000, image: '🪐', category: 'VIP' },
    { id: 'gift-138', name: 'Iate', price: 5000, image: '🛥️', category: 'VIP' },
    { id: 'gift-139', name: 'Galáxia', price: 6000, image: '🌠', category: 'VIP' },
    { id: 'gift-140', name: 'Coroa Real', price: 8000, image: '🤴', category: 'VIP' },
    { id: 'gift-141', name: 'Diamante VIP', price: 10000, image: '💎', category: 'VIP' },
    { id: 'gift-142', name: 'Ilha Particular', price: 15000, image: '🏝️', category: 'VIP' },
    { id: 'gift-143', name: 'Cavalo Alado', price: 25000, image: '🦄', category: 'VIP' },
    { id: 'gift-144', name: 'Tigre Dourado', price: 40000, image: '🐅', category: 'VIP' },
    { id: 'gift-145', name: 'Nave Espacial', price: 75000, image: '🛸', category: 'VIP' },
    { id: 'gift-146', name: 'Estrela Cadente', price: 22000, image: '🌠', category: 'VIP' },
    { id: 'gift-147', name: 'Cometa', price: 35000, image: '☄️', category: 'VIP' },
    { id: 'gift-148', name: 'Buraco Negro', price: 99999, image: '⚫', category: 'VIP' },
    { id: 'gift-149', name: 'Tesouro', price: 50000, image: '👑', category: 'VIP' },
    { id: 'gift-150', name: 'Pégaso', price: 60000, image: '🦄', category: 'VIP' },
    { id: 'gift-151', name: 'Grifo', price: 65000, image: '🦅', category: 'VIP' },
    { id: 'gift-152', name: 'Kraken', price: 70000, image: '🐙', category: 'VIP' },
    { id: 'gift-153', name: 'Hidra', price: 80000, image: '🐉', category: 'VIP' },
    { id: 'gift-154', name: 'Sereia', price: 45000, image: '🧜‍♀️', category: 'VIP' },
    { id: 'gift-155', name: 'Gênio', price: 55000, image: '🧞', category: 'VIP' },
    { id: 'gift-156', name: 'Anjo', price: 48000, image: '👼', category: 'VIP' },
    { id: 'gift-157', name: 'Excalibur', price: 42000, image: '🗡️', category: 'VIP' },
    { id: 'gift-158', name: 'Martelo de Thor', price: 68000, image: '🔨', category: 'VIP' },
    { id: 'gift-159', name: 'Tridente de Poseidon', price: 72000, image: '🔱', category: 'VIP' },
    { id: 'gift-160', name: 'Arco de Artemis', price: 62000, image: '🏹', category: 'VIP' },
    { id: 'gift-161', name: 'Elmo de Hades', price: 58000, image: '🎩', category: 'VIP' },
    { id: 'gift-162', name: 'Sandálias de Hermes', price: 52000, image: '👟', category: 'VIP' },
    { id: 'gift-163', name: 'Velo de Ouro', price: 90000, image: '🏆', category: 'VIP' },
    { id: 'gift-164', name: 'Maçã Dourada', price: 43000, image: '🍏', category: 'VIP' },
    { id: 'gift-165', name: 'Caixa de Pandora', price: 85000, image: '🎁', category: 'VIP' },
    { id: 'gift-166', name: 'Foguete Espacial', price: 25000, image: '🚀', category: 'VIP' },
    { id: 'gift-167', name: 'Disco Voador', price: 30000, image: '🛸', category: 'VIP' },
    { id: 'gift-168', name: 'Jet Ski', price: 700, image: '🚤', category: 'VIP' },
    { id: 'gift-169', name: 'Ilha Flutuante', price: 16000, image: '🏝️', category: 'VIP' },
    { id: 'gift-170', name: 'Trem Bala', price: 9000, image: '🚄', category: 'VIP' },
    { id: 'gift-171', name: 'Dirigível', price: 11000, image: '🎈', category: 'VIP' },

    { id: 'gift-172', name: 'Explosão de Confete', price: 19000, image: '🎉', category: 'Efeito' },
    { id: 'gift-173', name: 'Invocação de Dragão', price: 80000, image: '🐲', category: 'Efeito' },
    { id: 'gift-174', name: 'Coração Gigante', price: 28000, image: '❤️‍🔥', category: 'Efeito' },
    { id: 'gift-175', name: 'Beijo de Anjo', price: 23000, image: '😘', category: 'Efeito' },
    { id: 'gift-176', name: 'Dança dos Robôs', price: 33000, image: '🤖', category: 'Efeito' },
    { id: 'gift-177', name: 'Portal Galáctico', price: 42000, image: '🌀', category: 'Efeito' },
    { id: 'gift-178', name: 'Ataque de Tubarão', price: 37000, image: '🦈', category: 'Efeito' },
    { id: 'gift-179', name: 'Nuvem de Trovão', price: 31000, image: '⛈️', category: 'Efeito' },
    { id: 'gift-180', name: 'Flor de Lótus', price: 21000, image: '🌸', category: 'Efeito' },
    { id: 'gift-181', name: 'Chuva de Rosas', price: 26000, image: '🌹', category: 'Efeito' },
    { id: 'gift-182', name: 'Show de Luzes', price: 34000, image: '🎇', category: 'Efeito' },

    { id: 'gift-183', name: 'Entrada de Carro de Luxo', price: 1000, image: '🏎️', category: 'Entrada' },
    { id: 'gift-184', name: 'Entrada Fênix de Fogo', price: 5000, image: '🔥', category: 'Entrada' },
    { id: 'gift-185', name: 'Entrada Dragão Místico', price: 10000, image: '🐉', category: 'Entrada' },
    { id: 'gift-186', name: 'Tapete Mágico', price: 12000, image: '🧞', category: 'Entrada' },
    { id: 'gift-187', name: 'Entrada de Moto Esportiva', price: 2000, image: '🏍️', category: 'Entrada' },
    { id: 'gift-188', name: 'Chegada de Limousine', price: 8000, image: '🚘', category: 'Entrada' },
    { id: 'gift-189', name: 'Pouso de Pégaso', price: 15000, image: '🦄', category: 'Entrada' },
    { id: 'gift-190', name: 'Teletransporte', price: 7000, image: '🌀', category: 'Entrada' },
    { id: 'gift-191', name: 'Surfando na Onda', price: 6000, image: '🏄', category: 'Entrada' },
    { id: 'gift-192', name: 'Skate Voador', price: 4000, image: '🛹', category: 'Entrada' },
    { id: 'gift-193', name: 'Chegada de Tanque', price: 9000, image: '💣', category: 'Entrada' },
    { id: 'gift-194', name: 'Nuvem Voadora', price: 3000, image: '☁️', category: 'Entrada' },
    { id: 'gift-195', name: 'Carruagem Real', price: 11000, image: '👑', category: 'Entrada' },
    { id: 'gift-196', name: 'Chegada de Submarino', price: 13000, image: '🌊', category: 'Entrada' },
    { id: 'gift-197', name: 'Trono Flutuante', price: 18000, image: '✨', category: 'Entrada' },
    { id: 'gift-198', name: 'Jetpack', price: 5500, image: '🚀', category: 'Entrada' },
    { id: 'gift-199', name: 'Aparição Fantasma', price: 4500, image: '👻', category: 'Entrada' },
    { id: 'gift-200', name: 'Explosão de Flores', price: 3500, image: '🌸', category: 'Entrada' },
    { id: 'gift-201', name: 'Caminho de Estrelas', price: 6500, image: '⭐', category: 'Entrada' }
];

export const QUANTITY_OPTIONS = [1, 10, 99, 188, 520, 1314];