
import { Gift, GiftCategory, ChatMessage } from './types.js';
import React from 'react';
import { 
    GiftIcon, 
    // Import custom icons if they exist in icons.tsx, otherwise we rely on emojis/strings provided
} from './components/icons.js';

// Placeholder components for complex SVG gifts if not imported
const RocketGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "🚀");
const PrivateJetGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "✈️");
const RingGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "💍");
const LionGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "🦁");
const SportsCarGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "🏎️");
const PhoenixGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "🦅");
const SuperCarGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "🚘");
const DragonGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "🐉");
const CastleGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "🏰");
const UniverseGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "🌌");
const HelicopterGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "🚁");
const PlanetGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "🪐");
const YachtGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "🛥️");
const GalaxyGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "🌠");
const KingsCrownGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "👑");
const PremiumDiamondGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "💎");
const PrivateIslandGiftIcon = () => React.createElement('span', { className: "text-4xl" }, "🏝️");
const LuxuryCarEntryIcon = () => React.createElement('span', { className: "text-4xl" }, "🚔");
const FirePhoenixEntryIcon = () => React.createElement('span', { className: "text-4xl" }, "🔥");
const DragonEntryIcon = () => React.createElement('span', { className: "text-4xl" }, "🐲");

export const GIFT_CATEGORIES: GiftCategory[] = [
  { id: 'Popular', label: 'Popular' },
  { id: 'Luxo', label: 'Luxo' },
  { id: 'Atividade', label: 'Atividade' },
  { id: 'VIP', label: 'VIP' },
  { id: 'Efeito', label: 'Efeito' },
  { id: 'Entrada', label: 'Entrada' },
  { id: 'Galeria', label: 'Galeria' }
];

export const GIFTS: Gift[] = [
    { id: 'gift-1', name: 'Coração', price: 1, icon: '❤️', category: 'Popular' },
    { id: 'gift-2', name: 'Café', price: 3, icon: '☕', category: 'Popular' },
    { id: 'gift-3', name: 'Milho', price: 2, icon: '🍿', category: 'Popular' },
    { id: 'gift-4', name: 'Rosa', price: 5, icon: '🌷', category: 'Popular' },
    { id: 'gift-5', name: 'Flor', price: 7, icon: '🌸', category: 'Popular' },
    { id: 'gift-6', name: 'Donut', price: 8, icon: '🍩', category: 'Popular' },
    { id: 'gift-7', name: 'Balão', price: 9, icon: '🎈', category: 'Popular' },
    { id: 'gift-8', name: 'Batom', price: 10, icon: '💄', category: 'Popular' },
    { id: 'gift-9', name: 'Sinal de Luz do Ventilador', price: 10, icon: '🌟', category: 'Popular' },
    { id: 'gift-10', name: 'Chocolate', price: 12, icon: '🍫', category: 'Popular' },
    { id: 'gift-11', name: 'Sorvete', price: 15, icon: '🍦', category: 'Popular' },
    { id: 'gift-12', name: 'Lanche', price: 20, icon: '🍔', category: 'Popular' },
    { id: 'gift-13', name: 'Perfume', price: 25, icon: '🧴', category: 'Popular' },
    { id: 'gift-14', name: 'Pirulito', price: 30, icon: '🍭', category: 'Popular' },
    { id: 'gift-15', name: 'Pizza', price: 35, icon: '🍕', category: 'Popular' },
    { id: 'gift-16', name: 'Microfone', price: 40, icon: '🎤', category: 'Popular' },
    { id: 'gift-17', name: 'Alvo', price: 50, icon: '🎯', category: 'Popular' },
    { id: 'gift-18', name: 'Câmera', price: 60, icon: '📸', category: 'Popular' },
    { id: 'gift-19', name: 'Óculos de Sol', price: 80, icon: '😎', category: 'Popular' },
    { id: 'gift-20', name: 'Panda', price: 65, icon: '🐼', category: 'Popular' },
    { id: 'gift-21', name: 'Coala', price: 68, icon: '🐨', category: 'Popular' },
    { id: 'gift-22', name: 'Fatia de Pizza', price: 10, icon: '🍕', category: 'Popular' },
    { id: 'gift-23', name: 'Taco', price: 15, icon: '🌮', category: 'Popular' },
    { id: 'gift-24', name: 'Biscoito', price: 5, icon: '🍪', category: 'Popular' },
    { id: 'gift-25', name: 'Cupcake', price: 8, icon: '🧁', category: 'Popular' },
    { id: 'gift-26', name: 'Morango', price: 12, icon: '🍓', category: 'Popular' },
    { id: 'gift-27', name: 'Abacate', price: 18, icon: '🥑', category: 'Popular' },
    { id: 'gift-28', name: 'Brócolis', price: 4, icon: '🥦', category: 'Popular' },
    { id: 'gift-29', name: 'Baguete', price: 6, icon: '🥖', category: 'Popular' },
    { id: 'gift-30', name: 'Pretzel', price: 7, icon: '🥨', category: 'Popular' },
    { id: 'gift-31', name: 'Queijo', price: 11, icon: '🧀', category: 'Popular' },
    { id: 'gift-32', name: 'Waffle', price: 14, icon: '🧇', category: 'Popular' },
    { id: 'gift-33', name: 'Panquecas', price: 16, icon: '🥞', category: 'Popular' },
    { id: 'gift-34', name: 'Bacon', price: 19, icon: '🥓', category: 'Popular' },
    { id: 'gift-35', name: 'Cachorro-quente', price: 22, icon: '🌭', category: 'Popular' },
    { id: 'gift-36', name: 'Batata Frita', price: 9, icon: '🍟', category: 'Popular' },
    { id: 'gift-37', name: 'Sanduíche', price: 24, icon: '🥪', category: 'Popular' },
    { id: 'gift-38', name: 'Dango', price: 13, icon: '🍡', category: 'Popular' },
    { id: 'gift-39', name: 'Onigiri', price: 5, icon: '🍙', category: 'Popular' },
    { id: 'gift-40', name: 'Camarão Frito', price: 28, icon: '🍤', category: 'Popular' },
    { id: 'gift-41', name: 'Sushi', price: 33, icon: '🍣', category: 'Popular' },
    { id: 'gift-42', name: 'Taça de Sorvete', price: 17, icon: '🍨', category: 'Popular' },
    { id: 'gift-43', name: 'Torta', price: 21, icon: '🥧', category: 'Popular' },
    { id: 'gift-44', name: 'Doce', price: 3, icon: '🍬', category: 'Popular' },
    { id: 'gift-45', name: 'Mel', price: 26, icon: '🍯', category: 'Popular' },
    { id: 'gift-46', name: 'Copo de Leite', price: 8, icon: '🥛', category: 'Popular' },
    { id: 'gift-47', name: 'Chá Verde', price: 10, icon: '🍵', category: 'Popular' },
    { id: 'gift-48', name: 'Saquê', price: 29, icon: '🍶', category: 'Popular' },
    { id: 'gift-49', name: 'Cerveja', price: 15, icon: '🍺', category: 'Popular' },
    { id: 'gift-50', name: 'Milkshake', price: 22, icon: '🥤', category: 'Popular' },
    { id: 'gift-51', name: 'Croissant', price: 11, icon: '🥐', category: 'Popular' },
    { id: 'gift-52', name: 'Uvas', price: 14, icon: '🍇', category: 'Popular' },
    { id: 'gift-53', name: 'Frango Frito', price: 27, icon: '🍗', category: 'Popular' },
    { id: 'gift-54', name: 'Melancia', price: 10, icon: '🍉', category: 'Popular' },

    { id: 'gift-55', name: 'Bola de Basquete', price: 70, icon: '🏀', category: 'Atividade' },
    { id: 'gift-56', name: 'Bola', price: 75, icon: '⚽', category: 'Atividade' },
    { id: 'gift-57', name: 'Túmulo', price: 99, icon: '🪦', category: 'Atividade' },
    { id: 'gift-58', name: 'Bicicleta', price: 110, icon: '🚲', category: 'Atividade' },
    { id: 'gift-59', name: 'Haltere', price: 120, icon: '💪', category: 'Atividade' },
    { id: 'gift-60', name: 'Skate', price: 130, icon: '🛹', category: 'Atividade' },
    { id: 'gift-61', name: 'Prancha de Surf', price: 140, icon: '🏄', category: 'Atividade' },
    { id: 'gift-62', name: 'Luva de Boxe', price: 160, icon: '🥊', category: 'Atividade' },
    { id: 'gift-63', name: 'Taco de Golfe', price: 180, icon: '🏌️', category: 'Atividade' },
    { id: 'gift-64', name: 'Capacete de Corrida', price: 210, icon: '⛑️', category: 'Atividade' },
    { id: 'gift-65', name: 'Bola de Tênis', price: 85, icon: '🎾', category: 'Atividade' },
    { id: 'gift-66', name: 'Boliche', price: 95, icon: '🎳', category: 'Atividade' },
    { id: 'gift-67', name: 'Bola de Rugby', price: 105, icon: '🏉', category: 'Atividade' },
    { id: 'gift-68', name: 'Voleibol', price: 90, icon: '🏐', category: 'Atividade' },
    { id: 'gift-69', name: 'Beisebol', price: 80, icon: '⚾', category: 'Atividade' },
    { id: 'gift-70', name: 'Pingue-pongue', price: 78, icon: '🏓', category: 'Atividade' },
    { id: 'gift-71', name: 'Badminton', price: 82, icon: '🏸', category: 'Atividade' },
    { id: 'gift-72', name: 'Hóquei no Gelo', price: 150, icon: '🏒', category: 'Atividade' },
    { id: 'gift-73', name: 'Hóquei de Campo', price: 145, icon: '🏑', category: 'Atividade' },
    { id: 'gift-74', name: 'Lacrosse', price: 155, icon: '🥍', category: 'Atividade' },
    { id: 'gift-75', name: 'Críquete', price: 115, icon: '🏏', category: 'Atividade' },
    { id: 'gift-76', name: 'Rede de Gol', price: 190, icon: '🥅', category: 'Atividade' },
    { id: 'gift-77', name: 'Pipa', price: 65, icon: '🪁', category: 'Atividade' },
    { id: 'gift-78', name: 'Frisbee', price: 55, icon: '🥏', category: 'Atividade' },
    { id: 'gift-79', name: 'Trenzinho', price: 220, icon: '🛷', category: 'Atividade' },
    { id: 'gift-80', name: 'Pedra de Curling', price: 230, icon: '🥌', category: 'Atividade' },
    { id: 'gift-81', name: 'Esquis', price: 250, icon: '🎿', category: 'Atividade', triggersAutoFollow: true },
    { id: 'gift-82', name: 'Dardos', price: 45, icon: '🎯', category: 'Atividade' },
    { id: 'gift-83', name: 'Ioiô', price: 35, icon: '🪀', category: 'Atividade' },
    { id: 'gift-84', name: 'Bumerangue', price: 40, icon: '🪃', category: 'Atividade' },
    { id: 'gift-85', name: 'Trenó', price: 170, icon: '🛷', category: 'Atividade' },
    { id: 'gift-86', name: 'Arco e Flecha', price: 190, icon: '🏹', category: 'Atividade' },
    { id: 'gift-87', name: 'Patins', price: 135, icon: '🛼', category: 'Atividade' },

    { id: 'gift-88', name: 'Urso', price: 500, icon: '🧸', category: 'Luxo' },
    { id: 'gift-89', name: 'Boia', price: 800, icon: '🍩', category: 'Luxo' },
    { id: 'gift-90', name: 'Champanhe', price: 1200, icon: '🍾', category: 'Luxo' },
    { id: 'gift-91', name: 'Gema de Nível', price: 1500, icon: '💎', category: 'Luxo' },
    { id: 'gift-92', name: 'Relógio', price: 2000, icon: '⌚', category: 'Luxo' },
    { id: 'gift-93', name: 'Bolsa', price: 2500, icon: '👜', category: 'Luxo' },
    { id: 'gift-94', name: 'Moto', price: 3000, icon: '🛵', category: 'Luxo' },
    { id: 'gift-95', name: 'Violino', price: 3500, icon: '🎻', category: 'Luxo' },
    { id: 'gift-96', name: 'Salto Alto', price: 4000, icon: '👠', category: 'Luxo' },
    { id: 'gift-97', name: 'Piano', price: 4500, icon: '🎹', category: 'Luxo' },
    { id: 'gift-98', name: 'Colar', price: 4800, icon: '📿', category: 'Luxo' },
    { id: 'gift-99', name: 'Coroa', price: 5000, icon: '👑', category: 'Luxo', triggersAutoFollow: true },
    { id: 'gift-100', name: 'Bolsa de Grife', price: 6000, icon: '👜', category: 'Luxo' },
    { id: 'gift-101', name: 'Diamante Azul', price: 6000, icon: '💠', category: 'Luxo' },
    { id: 'gift-102', name: 'Carro Esportivo', price: 8888, icon: '🏎️', category: 'Luxo', triggersAutoFollow: true },
    { id: 'gift-103', name: 'Jóia Rara', price: 12000, icon: '💍', category: 'Luxo', triggersAutoFollow: true },
    { id: 'gift-104', name: 'Barco a Vela', price: 9000, icon: '⛵', category: 'Luxo', triggersAutoFollow: true },
    { id: 'gift-105', name: 'Navio de Cruzeiro', price: 15000, icon: '🛳️', category: 'Luxo' },
    { id: 'gift-106', name: 'Sino', price: 1800, icon: '🔔', category: 'Luxo' },
    { id: 'gift-107', name: 'Trompete', price: 2200, icon: '🎺', category: 'Luxo' },
    { id: 'gift-108', name: 'Saxofone', price: 2800, icon: '🎷', category: 'Luxo' },
    { id: 'gift-109', name: 'Acordeão', price: 3200, icon: '🪗', category: 'Luxo' },
    { id: 'gift-110', name: 'Harpa', price: 4200, icon: '🎻', category: 'Luxo' },
    { id: 'gift-111', name: 'Xadrez', price: 1000, icon: '♟️', category: 'Luxo' },
    { id: 'gift-112', name: 'Jóia', price: 7500, icon: '💎', category: 'Luxo' },
    { id: 'gift-113', name: 'Mala de Dinheiro', price: 10000, icon: '💰', category: 'Luxo' },
    { id: 'gift-114', name: 'Carta de Baralho', price: 900, icon: '🃏', category: 'Luxo' },
    { id: 'gift-115', name: 'Telescópio', price: 5500, icon: '🔭', category: 'Luxo' },
    { id: 'gift-116', name: 'Microscópio', price: 5200, icon: '🔬', category: 'Luxo' },
    { id: 'gift-117', name: 'Ampulheta', price: 1300, icon: '⏳', category: 'Luxo' },
    { id: 'gift-118', name: 'Despertador', price: 1100, icon: '⏰', category: 'Luxo' },
    { id: 'gift-119', name: 'Globo', price: 3800, icon: '🌍', category: 'Luxo' },
    { id: 'gift-120', name: 'Balão de Ar Quente', price: 4600, icon: '🎈', category: 'Luxo' },
    { id: 'gift-121', name: 'Troféu', price: 9999, icon: '🏆', category: 'Luxo' },
    { id: 'gift-122', name: 'Barra de Ouro', price: 7000, icon: '🧈', category: 'Luxo' },
    { id: 'gift-123', name: 'Cofre de Diamantes', price: 11000, icon: '💰', category: 'Luxo' },
    { id: 'gift-124', name: 'Chave do Carro', price: 9500, icon: '🔑', category: 'Luxo' },
    { id: 'gift-125', name: 'Cetro Real', price: 13000, icon: '👑', category: 'Luxo' },
    { id: 'gift-202', name: 'Vulcão de Dinheiro', price: 20000, icon: '🌋💰', category: 'Luxo', triggersAutoFollow: true },

    { id: 'gift-126', name: 'Foguete', price: 500, icon: '🚀', category: 'VIP', component: React.createElement(RocketGiftIcon), triggersAutoFollow: true },
    { id: 'gift-127', name: 'Jato Privado', price: 600, icon: '✈️', category: 'VIP', component: React.createElement(PrivateJetGiftIcon) },
    { id: 'gift-128', name: 'Anel', price: 750, icon: '💍', category: 'VIP', component: React.createElement(RingGiftIcon) },
    { id: 'gift-129', name: 'Leão', price: 800, icon: '🦁', category: 'VIP', component: React.createElement(LionGiftIcon) },
    { id: 'gift-130', name: 'Carro', price: 1000, icon: '🚗', category: 'VIP', component: React.createElement(SportsCarGiftIcon) },
    { id: 'gift-131', name: 'Fênix', price: 1200, icon: '🔥', category: 'VIP', component: React.createElement(PhoenixGiftIcon) },
    { id: 'gift-132', name: 'Supercarro', price: 1500, icon: '🏎️', category: 'VIP', component: React.createElement(SuperCarGiftIcon) },
    { id: 'gift-133', name: 'Dragão', price: 1800, icon: '🐉', category: 'VIP', component: React.createElement(DragonGiftIcon) },
    { id: 'gift-134', name: 'Castelo', price: 2000, icon: '🏰', category: 'VIP', component: React.createElement(CastleGiftIcon), triggersAutoFollow: true },
    { id: 'gift-135', name: 'Universo', price: 2500, icon: '🌌', category: 'VIP', component: React.createElement(UniverseGiftIcon) },
    { id: 'gift-136', name: 'Helicóptero', price: 3000, icon: '🚁', category: 'VIP', component: React.createElement(HelicopterGiftIcon) },
    { id: 'gift-137', name: 'Planeta', price: 4000, icon: '🪐', category: 'VIP', component: React.createElement(PlanetGiftIcon) },
    { id: 'gift-138', name: 'Iate', price: 5000, icon: '🛥️', category: 'VIP', component: React.createElement(YachtGiftIcon) },
    { id: 'gift-139', name: 'Galáxia', price: 6000, icon: '🌠', category: 'VIP', component: React.createElement(GalaxyGiftIcon) },
    { id: 'gift-140', name: 'Coroa Real', price: 8000, icon: '🤴', category: 'VIP', component: React.createElement(KingsCrownGiftIcon) },
    { id: 'gift-141', name: 'Diamante VIP', price: 10000, icon: '💎', category: 'VIP', component: React.createElement(PremiumDiamondGiftIcon) },
    { id: 'gift-142', name: 'Ilha Particular', price: 15000, icon: '🏝️', category: 'VIP', component: React.createElement(PrivateIslandGiftIcon) },
    { id: 'gift-143', name: 'Cavalo Alado', price: 25000, icon: '🦄', category: 'VIP' },
    { id: 'gift-144', name: 'Tigre Dourado', price: 40000, icon: '🐅', category: 'VIP' },
    { id: 'gift-145', name: 'Nave Espacial', price: 75000, icon: '🛸', category: 'VIP' },
    { id: 'gift-146', name: 'Estrela Cadente', price: 22000, icon: '🌠', category: 'VIP' },
    { id: 'gift-147', name: 'Cometa', price: 35000, icon: '☄️', category: 'VIP' },
    { id: 'gift-148', name: 'Buraco Negro', price: 99999, icon: '⚫', category: 'VIP' },
    { id: 'gift-149', name: 'Tesouro', price: 50000, icon: '👑', category: 'VIP' },
    { id: 'gift-150', name: 'Pégaso', price: 60000, icon: '🦄', category: 'VIP' },
    { id: 'gift-151', name: 'Grifo', price: 65000, icon: '🦅', category: 'VIP' },
    { id: 'gift-152', name: 'Kraken', price: 70000, icon: '🐙', category: 'VIP' },
    { id: 'gift-153', name: 'Hidra', price: 80000, icon: '🐉', category: 'VIP' },
    { id: 'gift-154', name: 'Sereia', price: 45000, icon: '🧜‍♀️', category: 'VIP' },
    { id: 'gift-155', name: 'Gênio', price: 55000, icon: '🧞', category: 'VIP' },
    { id: 'gift-156', name: 'Anjo', price: 48000, icon: '👼', category: 'VIP' },
    { id: 'gift-157', name: 'Excalibur', price: 42000, icon: '🗡️', category: 'VIP' },
    { id: 'gift-158', name: 'Martelo de Thor', price: 68000, icon: '🔨', category: 'VIP' },
    { id: 'gift-159', name: 'Tridente de Poseidon', price: 72000, icon: '🔱', category: 'VIP' },
    { id: 'gift-160', name: 'Arco de Artemis', price: 62000, icon: '🏹', category: 'VIP' },
    { id: 'gift-161', name: 'Elmo de Hades', price: 58000, icon: '🎩', category: 'VIP' },
    { id: 'gift-162', name: 'Sandálias de Hermes', price: 52000, icon: '👟', category: 'VIP' },
    { id: 'gift-163', name: 'Velo de Ouro', price: 90000, icon: '🏆', category: 'VIP' },
    { id: 'gift-164', name: 'Maçã Dourada', price: 43000, icon: '🍏', category: 'VIP' },
    { id: 'gift-165', name: 'Caixa de Pandora', price: 85000, icon: '🎁', category: 'VIP' },
    { id: 'gift-166', name: 'Foguete Espacial', price: 25000, icon: '🚀', category: 'VIP' },
    { id: 'gift-167', name: 'Disco Voador', price: 30000, icon: '🛸', category: 'VIP' },
    { id: 'gift-168', name: 'Jet Ski', price: 700, icon: '🚤', category: 'VIP' },
    { id: 'gift-169', name: 'Ilha Flutuante', price: 16000, icon: '🏝️', category: 'VIP' },
    { id: 'gift-170', name: 'Trem Bala', price: 9000, icon: '🚄', category: 'VIP' },
    { id: 'gift-171', name: 'Dirigível', price: 11000, icon: '🎈', category: 'VIP' },

    { id: 'gift-172', name: 'Explosão de Confete', price: 19000, icon: '🎉', category: 'Efeito' },
    { id: 'gift-173', name: 'Invocação de Dragão', price: 80000, icon: '🐲', category: 'Efeito' },
    { id: 'gift-174', name: 'Coração Gigante', price: 28000, icon: '❤️‍🔥', category: 'Efeito' },
    { id: 'gift-175', name: 'Beijo de Anjo', price: 23000, icon: '😘', category: 'Efeito' },
    { id: 'gift-176', name: 'Dança dos Robôs', price: 33000, icon: '🤖', category: 'Efeito' },
    { id: 'gift-177', name: 'Portal Galáctico', price: 42000, icon: '🌀', category: 'Efeito' },
    { id: 'gift-178', name: 'Ataque de Tubarão', price: 37000, icon: '🦈', category: 'Efeito' },
    { id: 'gift-179', name: 'Nuvem de Trovão', price: 31000, icon: '⛈️', category: 'Efeito' },
    { id: 'gift-180', name: 'Flor de Lótus', price: 21000, icon: '🌸', category: 'Efeito' },
    { id: 'gift-181', name: 'Chuva de Rosas', price: 26000, icon: '🌹', category: 'Efeito' },
    { id: 'gift-182', name: 'Show de Luzes', price: 34000, icon: '🎇', category: 'Efeito' },

    { id: 'gift-183', name: 'Entrada de Carro de Luxo', price: 1000, icon: '🏎️', category: 'Entrada', component: React.createElement(LuxuryCarEntryIcon) },
    { id: 'gift-184', name: 'Entrada Fênix de Fogo', price: 5000, icon: '🔥', category: 'Entrada', component: React.createElement(FirePhoenixEntryIcon) },
    { id: 'gift-185', name: 'Entrada Dragão Místico', price: 10000, icon: '🐉', category: 'Entrada', component: React.createElement(DragonEntryIcon) },
    { id: 'gift-186', name: 'Tapete Mágico', price: 12000, icon: '🧞', category: 'Entrada' },
    { id: 'gift-187', name: 'Entrada de Moto Esportiva', price: 2000, icon: '🏍️', category: 'Entrada' },
    { id: 'gift-188', name: 'Chegada de Limousine', price: 8000, icon: '🚘', category: 'Entrada' },
    { id: 'gift-189', name: 'Pouso de Pégaso', price: 15000, icon: '🦄', category: 'Entrada' },
    { id: 'gift-190', name: 'Teletransporte', price: 7000, icon: '🌀', category: 'Entrada' },
    { id: 'gift-191', name: 'Surfando na Onda', price: 6000, icon: '🏄', category: 'Entrada' },
    { id: 'gift-192', name: 'Skate Voador', price: 4000, icon: '🛹', category: 'Entrada' },
    { id: 'gift-193', name: 'Chegada de Tanque', price: 9000, icon: '💣', category: 'Entrada' },
    { id: 'gift-194', name: 'Nuvem Voadora', price: 3000, icon: '☁️', category: 'Entrada' },
    { id: 'gift-195', name: 'Carruagem Real', price: 11000, icon: '👑', category: 'Entrada' },
    { id: 'gift-196', name: 'Chegada de Submarino', price: 13000, icon: '🌊', category: 'Entrada' },
    { id: 'gift-197', name: 'Trono Flutuante', price: 18000, icon: '✨', category: 'Entrada' },
    { id: 'gift-198', name: 'Jetpack', price: 5500, icon: '🚀', category: 'Entrada' },
    { id: 'gift-199', name: 'Aparição Fantasma', price: 4500, icon: '👻', category: 'Entrada' },
    { id: 'gift-200', name: 'Explosão de Flores', price: 3500, icon: '🌸', category: 'Entrada' },
    { id: 'gift-201', name: 'Caminho de Estrelas', price: 6500, icon: '⭐', category: 'Entrada' }
];

export const QUANTITY_OPTIONS = [1, 10, 99, 188, 520, 1314];

export const INITIAL_MESSAGES: ChatMessage[] = [
  { id: '1', user: 'JuFe', text: 'entrou na sala.', level: 2 },
  { id: '2', user: 'Marcos', text: 'Oi! Tudo bem?', level: 5 },
  { id: '3', user: 'Ana', text: 'Que live legal!', level: 1 }
];
