# Configuração básica do SRS
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

# Configuração do HTTP API
http_api {
    enabled         on;
    listen          1985;
}

# Configuração do HTTP Server
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

# Configuração do RTC Server
rtc_server {
    enabled on;
    listen 8000;
}

# Configuração do VHOST
vhost __defaultVhost__ {
    # Configuração do HLS
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    10;
        hls_window      60;
        hls_cleanup     on;
    }
    
    # Configuração do DVR
    dvr {
        enabled         on;
        dvr_path       ./objs/nginx/html;
        dvr_plan       session;
        dvr_duration   30;
        dvr_wait_keyframe       on;
        time_jitter    full;
    }
    
    # Configuração do HTTP para este vhost
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }

    # Configuração do RTC para este vhost
    rtc {
        enabled         on;
        nack            on;
        twcc            on;
    }
}