# Main configuration for SRS
# @see https://ossrs.net/lts/en-us/docs/v5/doc/conf

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
    crossdomain     on;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

rtc_server {
    enabled on;
    listen 8000;
    # @see https://ossrs.net/lts/en-us/docs/v5/doc/webrtc#config-candidate
    candidate $CANDIDATE;
}

vhost __defaultVhost__ {
    # RTMP configuration
    rtmp {
        enabled     on;
        # @see https://ossrs.net/lts/en-us/docs/v5/doc/relay#rtmp-to-rtmp
        relay {
            enabled on;
            destination 127.0.0.1:1936;
        }
    }

    
    # HLS configuration
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html/hls;
        hls_fragment    10;
        hls_window      60;
        hls_cleanup     on;
        hls_nb_notify   64;
    }
    
    # HTTP-FLV configuration
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
        hstrs       on;
    }
    
    # DVR configuration
    dvr {
        enabled      on;
        dvr_path     ./objs/nginx/html/dvr;
        dvr_plan     segment;
        dvr_duration 30m;
        dvr_wait_keyframe  on;
    }
    
    # WebRTC configuration
    rtc {
        enabled     on;
        # @see https://ossrs.net/lts/en-us/docs/v5/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://ossrs.net/lts/en-us/docs/v5/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp on;
    }
    
    # Authentication for publishing
    # @see https://ossrs.net/lts/en-us/docs/v5/doc/delivery-hooks#http-callback
    http_hooks {
        enabled         on;
        on_connect      http://host.docker.internal:3000/api/hooks/connect;
        on_publish      http://host.docker.internal:3000/api/hooks/publish;
        on_unpublish    http://host.docker.internal:3000/api/hooks/unpublish;
        on_play         http://host.docker.internal:3000/api/hooks/play;
        on_stop         http://host.docker.internal:3000/api/hooks/stop;
        on_dvr          http://host.docker.internal:3000/api/hooks/dvr;
        on_hls          http://host.docker.internal:3000/api/hooks/hls;
    }
}
