# The main configuration for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
    crossdomain     on;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

# For RTMP streaming and play on H5 with WebRTC.
# @see https://ossrs.net/lts/zh-cn/docs/v5/doc/webrtc
rtc_server {
    enabled on;
    listen 8000; # UDP port
    # @see https://ossrs.net/lts/zh-cn/docs/v5/doc/webrtc#config-candidate
    candidate $CANDIDATE;
}

vhost __defaultVhost__ {
    # For play with WebRTC over SDP.
    # @see https://ossrs.net/lts/zh-cn/docs/v5/doc/webrtc#play-rtmp-to-webrtc
    rtc {
        enabled     on;
        rtmp_to_rtc on;
        rtc_to_rtmp off;
    }

    # For authentication when publishing.
    # @see https://ossrs.net/lts/zh-cn/docs/v5/doc/delivery-hooks#http-callback
    http_hooks {
        enabled         on;
        on_connect      http://api:3000/api/srs/on_connect;
        on_publish      http://api:3000/api/srs/on_publish;
        on_unpublish    http://api:3000/api/srs/on_unpublish;
        on_stop         http://api:3000/api/srs/on_stop;
    }

    # For authentication and authorization.
    # @see https://ossrs.net/lts/zh-cn/docs/v5/doc/dvr#http-callback
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}
